import type { AgentExecutionRecord, AuthoritativeSourceDefinition, Claim, ClaimDomain, Evidence, FetchedDocument, HttpSourceFetchRecord, KnowledgeAssertion, ManagerReviewRecord, RealityClass, RightsClassification, Source, SourceProvenanceChain } from '../types/hermes';
import { createClaim, createEvidence } from './projectEvidence';

export function sourceRights(source: Pick<AuthoritativeSourceDefinition, 'copyrightLicenseStatus' | 'bulkIngestionPermitted' | 'fullTextStoragePermitted' | 'chunkingPermitted' | 'accessType'>) {
  const permitted = source.accessType !== 'VIEW_ONLY_METADATA' && source.bulkIngestionPermitted && source.fullTextStoragePermitted && ['PUBLIC_DOMAIN','PERMITTED_OPEN','OPEN_LICENSE','PERMITTED_FULL_TEXT'].includes(source.copyrightLicenseStatus);
  const rightsClassification: RightsClassification = source.copyrightLicenseStatus === 'RIGHTS_REVIEW_REQUIRED' ? 'LICENSE_REVIEW_REQUIRED' : !permitted ? 'REFERENCE_ONLY' : source.copyrightLicenseStatus === 'PUBLIC_DOMAIN' ? 'REDISTRIBUTABLE' : 'CACHE_ALLOWED';
  return { permitted, rightsClassification, rightsStatus: permitted ? source.copyrightLicenseStatus : source.copyrightLicenseStatus === 'RIGHTS_REVIEW_REQUIRED' ? 'RIGHTS_REVIEW_REQUIRED' : 'RIGHTS_RESTRICTED_METADATA_ONLY', storagePolicy: { bulkIngestionPermitted: permitted, fullTextStoragePermitted: permitted, chunkingPermitted: permitted && source.chunkingPermitted } };
}
export function adaptAuthoritativeSource(input: AuthoritativeSourceDefinition): Source {
  const rights = sourceRights(input);
  return { sourceId: input.sourceId, sourceType: 'KNOWLEDGE_REGISTRY', title: input.title, ownerOrMaintainer: input.agencyOrOrganization || input.publisher, uri: input.URL, jurisdiction: input.jurisdiction, geographicScope: input.geographicScope, editionVersion: input.editionVersion, authorityClass: input.authorityLevel === 'PRIMARY_GOVERNMENT' ? 'REGIONAL_PUBLIC_DATA' : input.authorityLevel === 'PRIMARY_MANUFACTURER' ? 'MANUFACTURER_DATA' : 'TECHNICAL_REFERENCE', legacyAuthorityLevel: input.authorityLevel, licenseStatus: input.copyrightLicenseStatus, rightsClassification: rights.rightsClassification, storagePolicy: rights.storagePolicy, lastChecked: input.lastChecked, updateCadence: input.freshnessCategory, citationRequirements: input.citationRequirements };
}
export interface EvidenceScope { projectId: string; projectRevisionId: string; subjectEntityId: string; realityClass: RealityClass; recordedAt: string; }
export function adaptFetchedDocument(document: FetchedDocument, fetch: HttpSourceFetchRecord, source: Source, scope: EvidenceScope): Evidence {
  if (document.sourceId !== source.sourceId || fetch.sourceId !== source.sourceId || fetch.documentId !== document.documentId || fetch.checksumSha256 !== document.checksumSha256) throw new Error('Document/fetch/source lineage mismatch');
  const contentKind = fetch.fetchStatus === 'FAILED' ? 'FAILED_RETRIEVAL' : fetch.fetchStatus !== 'SUCCESS' || /RESTRICT|REVIEW|METADATA/.test(document.rightsStatus) || /RESTRICT|REVIEW|METADATA/.test(fetch.rightsStatus) || !source.storagePolicy.fullTextStoragePermitted ? 'METADATA_ONLY' : 'CONTENT';
  return createEvidence({ evidenceId: `EVID-${scope.projectId}-${scope.projectRevisionId}-${document.documentId}-${document.checksumSha256}`, projectId: scope.projectId, sourceId: source.sourceId, projectRevisionId: scope.projectRevisionId, relatedEntityIds: [scope.subjectEntityId], artifactUri: document.filePathOrKey, artifactHash: document.checksumSha256, mimeType: document.mimeType, capturedAt: document.retrievalTime, recordedAt: scope.recordedAt, rightsClassification: source.rightsClassification, realityClass: scope.realityClass, contentKind, lineage: { documentId: document.documentId, fetchId: fetch.fetchId } });
}
export function adaptKnowledgeAssertion(assertion: KnowledgeAssertion, evidence: Evidence, source: Source, scope: EvidenceScope): Claim {
  if (evidence.sourceId !== source.sourceId || evidence.lineage?.documentId !== assertion.sourceDocumentId || evidence.projectId !== scope.projectId || evidence.projectRevisionId !== scope.projectRevisionId || !evidence.relatedEntityIds.includes(scope.subjectEntityId)) throw new Error('Assertion evidence linkage mismatch');
  return createClaim({ claimId: `CLAIM-${scope.projectId}-${scope.projectRevisionId}-${assertion.assertionId}`, projectId: scope.projectId, projectRevisionId: scope.projectRevisionId, subjectEntityId: scope.subjectEntityId, domain: 'GENERAL', predicate: assertion.predicate, value: assertion.objectValue, units: assertion.units, recordedAt: scope.recordedAt, confidence: assertion.confidence, evidenceIds: [evidence.evidenceId], derivationMethod: 'MODEL_INFERENCE', sourceAuthorityClass: source.authorityClass, realityClass: scope.realityClass, softwareOrModelVersion: assertion.version, status: assertion.validationStatus === 'REJECTED' || assertion.validationStatus === 'CONTRADICTED' ? 'REJECTED' : 'PROPOSED', legacyProvenance: { assertionId: assertion.assertionId, validationStatus: assertion.validationStatus, chunkId: assertion.sourceChunkId, documentId: assertion.sourceDocumentId, sourceUrl: assertion.sourceUrl, effectiveDate: assertion.effectiveDate, pageOrSection: String(assertion.pageNumber ?? assertion.sectionTitle ?? ''), extractor: assertion.agentExtractorId } });
}
export function adaptProvenanceChain(chain: SourceProvenanceChain, evidence: Evidence) {
  if (chain.sourceId !== evidence.sourceId || chain.documentId !== evidence.lineage?.documentId || chain.sha256Hash !== evidence.artifactHash) throw new Error('Provenance chain mismatch');
  return { ...evidence.lineage, provenanceChainId: chain.chainId, chunkId: chain.chunkId, pageOrSection: chain.pageOrSection, assertionId: chain.assertionId, knowledgePackId: chain.knowledgePackId };
}
export function adaptLegacyClaim(input: { id: string; predicate: string; value: Claim['value']; provenanceSource?: string; verificationStatus?: string; priceSource?: string; confidence?: number }, scope: EvidenceScope, domain: ClaimDomain = 'GENERAL'): Claim {
  return createClaim({ claimId: input.id, projectId: scope.projectId, projectRevisionId: scope.projectRevisionId, subjectEntityId: scope.subjectEntityId, domain, predicate: input.predicate, value: input.value, recordedAt: scope.recordedAt, evidenceIds: [], derivationMethod: 'ASSUMED', sourceAuthorityClass: 'UNKNOWN', realityClass: 'HISTORICAL_REFERENCE', legacyProvenance: { source: input.provenanceSource ?? input.priceSource ?? '', status: input.verificationStatus ?? '', confidence: String(input.confidence ?? '') } });
}
export function adaptAgentExecution(record: AgentExecutionRecord, scope: EvidenceScope): Claim {
  return createClaim({ claimId: `CLAIM-${record.executionId}`, projectId: scope.projectId, projectRevisionId: scope.projectRevisionId, subjectEntityId: scope.subjectEntityId, domain: 'GENERAL', predicate: 'agent.proposal', value: record.structuredProposal, recordedAt: scope.recordedAt, evidenceIds: [], derivationMethod: 'MODEL_INFERENCE', sourceAuthorityClass: 'HERMES_INTERNAL', realityClass: /SIMULAT|MOCK|DETERMINISTIC/.test(record.executionMode) ? 'SIMULATION' : scope.realityClass, softwareOrModelVersion: `${record.modelProvider}/${record.modelName}`, legacyProvenance: { executionId: record.executionId, promptHash: record.promptHash, executionStatus: record.executionStatus, citations: JSON.stringify(record.citations), chunkIds: JSON.stringify(record.retrievedChunkIds) } });
}
export function adaptManagerReview(record: ManagerReviewRecord) {
  // Even PROFESSIONAL_REVIEW is merely a declared mode, not signed project evidence.
  return { reviewId: record.reviewId ?? record.id, reviewerId: record.managerRoleId, sourceAuthorityClass: 'HERMES_INTERNAL' as const, decision: record.decision ?? record.status, reviewMode: record.reviewMode, evidenceReviewed: structuredClone(record.evidenceReviewed), grantsProfessionalApproval: false, grantsAhjApproval: false };
}
