import { SwarmAgentEntity } from '../src/types/hermes';

export const FULL_SWARM_AGENTS: SwarmAgentEntity[] = [
  // HERMES PRIME
  {
    id: 'PRIME-ORCHESTRATOR-01',
    name: 'HERMES Prime Orchestrator',
    swarmGroup: 'Executive Control',
    specialty: 'Autonomous System Supervision & Gym Curriculum Control',
    status: 'RUNNING',
    confidence: 99.4,
    lastAction: 'Evaluating system skill gaps & scheduling next gym task',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },

  // PROJECT PLANNING
  {
    id: 'PLAN-REQ-01',
    name: 'Project Requirements Agent',
    swarmGroup: 'Project Planning',
    specialty: 'Owner Requirements Translation & Project Scope Definition',
    status: 'IDLE',
    confidence: 96.5,
    lastAction: 'Parsed project brief for 2-Story Tampa Residence',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'PLAN-PROG-02',
    name: 'Building Program Agent',
    swarmGroup: 'Project Planning',
    specialty: 'Room Area Programming & Spatial Balance Optimization',
    status: 'IDLE',
    confidence: 95.8,
    lastAction: 'Allocated 2,450 sq ft across Living, Kitchen, 3 Bed, 2.5 Bath',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'PLAN-FEAS-03',
    name: 'Site Feasibility Agent',
    swarmGroup: 'Project Planning',
    specialty: 'Zoning Setbacks, Height Restrictions & Coverage Limits',
    status: 'IDLE',
    confidence: 97.1,
    lastAction: 'Verified Tampa RS-60 zoning 25ft front setback compliance',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'PLAN-STRAT-04',
    name: 'Construction Strategy Agent',
    swarmGroup: 'Project Planning',
    specialty: 'Phasing Strategy, Long-Lead Scheduling & Trade Sequencing',
    status: 'IDLE',
    confidence: 94.9,
    lastAction: 'Established 20-stage sequential task graph execution path',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'PLAN-DEP-05',
    name: 'Project Dependency Agent',
    swarmGroup: 'Project Planning',
    specialty: 'Task Prerequisite Mapping & Critical Path Graph Generation',
    status: 'IDLE',
    confidence: 98.2,
    lastAction: 'Resolved foundation-to-underground plumbing dependency lock',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },

  // SITE / CIVIL
  {
    id: 'CIVIL-PARCEL-01',
    name: 'Parcel Boundaries Agent',
    swarmGroup: 'Site / Civil',
    specialty: 'Property Line Georeferencing & Easement Clearance',
    status: 'IDLE',
    confidence: 96.0,
    lastAction: 'Mapped 7,500 sq ft parcel GIS coordinates',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'CIVIL-SURVEY-02',
    name: 'Topographic Survey Agent',
    swarmGroup: 'Site / Civil',
    specialty: 'Elevation Contour Mapping & Benchmark Datum Establishment',
    status: 'IDLE',
    confidence: 95.4,
    lastAction: 'Established NAVD88 benchmark datum @ +9.5 ft elevation',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'CIVIL-GRADE-03',
    name: 'Grading Vector Agent',
    swarmGroup: 'Site / Civil',
    specialty: 'Surface Slope Calculation & Positive Drainage Flow Direction',
    status: 'IDLE',
    confidence: 97.8,
    lastAction: 'Calculated 2% site slope away from building foundation',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'CIVIL-STORM-04',
    name: 'Stormwater Hydraulics Agent',
    swarmGroup: 'Site / Civil',
    specialty: 'Rational Method Runoff Volume & Detention Basin Sizing',
    status: 'IDLE',
    confidence: 94.2,
    lastAction: 'Sized 10-year storm event retention swale',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'CIVIL-DRAIN-05',
    name: 'Drainage Inspector Agent',
    swarmGroup: 'Site / Civil',
    specialty: 'Site Drainage Slope Vector Verification & Runoff Audit',
    status: 'IDLE',
    confidence: 98.6,
    lastAction: 'Verified water runoff vectors reach municipal storm sewer',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'CIVIL-UTIL-06',
    name: 'Utility Connection Agent',
    swarmGroup: 'Site / Civil',
    specialty: 'Water Main Tap, Sewer Tie-in & Underground Electric Conduit Route',
    status: 'IDLE',
    confidence: 95.1,
    lastAction: 'Mapped 6" SDR-35 PVC sewer lateral connection @ 1/4" fall',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'CIVIL-EXCAV-07',
    name: 'Excavation Depth Agent',
    swarmGroup: 'Site / Civil',
    specialty: 'Footing Trench Trenching & Cut/Fill Balancing',
    status: 'IDLE',
    confidence: 96.3,
    lastAction: 'Calculated 42 cu yd cut volume for continuous footings',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'CIVIL-EARTH-08',
    name: 'Earthwork Quantity Agent',
    swarmGroup: 'Site / Civil',
    specialty: 'Compacted Fill Volume & Structural Gravel Bed Sizing',
    status: 'IDLE',
    confidence: 99.1,
    lastAction: 'Quantified 65 cu yd compacted lime rock fill base',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'CIVIL-LOGIST-09',
    name: 'Site Logistics & Access Agent',
    swarmGroup: 'Site / Civil',
    specialty: 'Concrete Truck Turning Radius, Laydown Area & Staging',
    status: 'IDLE',
    confidence: 94.7,
    lastAction: 'Designated 40ft wide staging area on north parcel edge',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },

  // ENVIRONMENT
  {
    id: 'ENV-CLIMATE-01',
    name: 'Climate Zone Agent',
    swarmGroup: 'Environment',
    specialty: 'ASHRAE Climate Zone Profile & Thermal Insulation Sizing',
    status: 'IDLE',
    confidence: 98.0,
    lastAction: 'Assigned Zone 1A Hot-Humid envelope resistance parameters',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'ENV-COASTAL-02',
    name: 'Coastal Exposure Agent',
    swarmGroup: 'Environment',
    specialty: 'Salt Spray Corrosion Resistance & SS316 Fastener Requirements',
    status: 'IDLE',
    confidence: 97.5,
    lastAction: 'Mandated SS316 stainless anchors for exterior exposure within 3 miles',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'ENV-FLOOD-03',
    name: 'Flood Risk Hydrodynamics Agent',
    swarmGroup: 'Environment',
    specialty: 'Base Flood Elevation (BFE) & Hydrostatic Relief Vents',
    status: 'IDLE',
    confidence: 98.9,
    lastAction: 'Set finish floor elevation +2.0 ft above BFE Zone AE',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'ENV-WIND-04',
    name: 'Wind Uplift Dynamics Agent',
    swarmGroup: 'Environment',
    specialty: 'FBC HVHZ 160 MPH Wind Load & Continuous Tie-Down Path',
    status: 'IDLE',
    confidence: 99.0,
    lastAction: 'Calculated 38.5 PSF roof uplift suction pressure @ corners',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'ENV-SEISMIC-05',
    name: 'Seismic Category Agent',
    swarmGroup: 'Environment',
    specialty: 'Seismic Design Category A Shear Anchor Check',
    status: 'IDLE',
    confidence: 96.8,
    lastAction: 'Verified low seismic risk Category A minimal lateral anchor requirement',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },

  // STRUCTURAL
  {
    id: 'STRUCT-FOUND-01',
    name: 'Foundation Design Agent',
    swarmGroup: 'Structural Engineering',
    specialty: 'Monolithic Slab, Stem Wall & Helical Pile Geometries',
    status: 'IDLE',
    confidence: 98.2,
    lastAction: 'Designed 20" x 12" continuous stem wall with #5 rebar stirrups',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'STRUCT-LOAD-02',
    name: 'Load Path Vector Agent',
    swarmGroup: 'Structural Engineering',
    specialty: 'Gravity & Lateral Load Vector Tracing Roof-to-Foundation',
    status: 'IDLE',
    confidence: 99.2,
    lastAction: 'Verified continuous tension tie load path via Simpson HDU hold-downs',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'STRUCT-SLAB-03',
    name: 'Slab & Deck Agent',
    swarmGroup: 'Structural Engineering',
    specialty: 'ACI 318 Post-Tensioned & Fiber-Reinforced Concrete Slabs',
    status: 'IDLE',
    confidence: 98.0,
    lastAction: 'Specified 5000 PSI concrete with 15-mil Stego Wrap vapor barrier',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'STRUCT-INSP-04',
    name: 'Structural Inspector Agent',
    swarmGroup: 'Independent Verification',
    specialty: 'Rebar Spacing, Concrete Cylinder Strength & Anchor Bolt Audits',
    status: 'IDLE',
    confidence: 99.5,
    lastAction: 'Audited slab anchor bolt spacing for FBC HVHZ compliance',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },

  // PLUMBING
  {
    id: 'PLUMB-ROUTE-01',
    name: 'Plumbing Routing Agent',
    swarmGroup: 'MEP Services',
    specialty: 'IPC Gravity Drainage Slope (1/4" per ft) & Riser Stack Routing',
    status: 'IDLE',
    confidence: 96.7,
    lastAction: 'Routed 3" PVC sanitary stack from second floor baths down to main drain',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'PLUMB-INSP-02',
    name: 'Plumbing Inspector Agent',
    swarmGroup: 'Independent Verification',
    specialty: 'IPC Hydraulic Fixture Unit Calculations & Vent Fall Verification',
    status: 'IDLE',
    confidence: 98.7,
    lastAction: 'Audited fixture unit drainage load & trap seal protection',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },

  // ELECTRICAL
  {
    id: 'ELEC-PANEL-01',
    name: 'Electrical Service & Panel Agent',
    swarmGroup: 'MEP Services',
    specialty: 'NEC 2023 200A 120/240V Service Entry, Feeders & Breaker Schedules',
    status: 'IDLE',
    confidence: 97.3,
    lastAction: 'Balanced 40-circuit panel load schedule with 25% spare capacity',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'ELEC-INSP-02',
    name: 'Electrical Inspector Agent',
    swarmGroup: 'Independent Verification',
    specialty: 'NEC Conduit Fill, AFCI/GFCI Protection & Voltage Drop Audits',
    status: 'IDLE',
    confidence: 99.1,
    lastAction: 'Verified AFCI protection on all bedroom branch circuits',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },

  // HVAC
  {
    id: 'HVAC-LOAD-01',
    name: 'HVAC Thermal Load Agent',
    swarmGroup: 'MEP Services',
    specialty: 'Manual J Cooling/Heating Load & Duct Static Pressure Design',
    status: 'IDLE',
    confidence: 96.1,
    lastAction: 'Calculated 3.5 Ton cooling load (1,400 CFM) for second floor zone',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'HVAC-INSP-02',
    name: 'HVAC Inspector Agent',
    swarmGroup: 'Independent Verification',
    specialty: 'Duct Leakage Testing & ASHRAE 62.2 Fresh Air Ventilation Audit',
    status: 'IDLE',
    confidence: 98.4,
    lastAction: 'Audited ERV fresh air intake clearance from exhaust vents',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },

  // QUANTITY & COMMERCIAL
  {
    id: 'COMM-BOM-01',
    name: 'Deterministic BOM Agent',
    swarmGroup: 'Commercial & Sourcing',
    specialty: 'Volumetric & Surface Extraction from 3D BIM Geometry',
    status: 'IDLE',
    confidence: 99.8,
    lastAction: 'Extracted 52 cu yd concrete & 2,840 sq ft drywall sheathing',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'COMM-SOURCING-02',
    name: 'Local Supply Chain Agent',
    swarmGroup: 'Commercial & Sourcing',
    specialty: 'Geographic Supplier Matching, Delivery Distances & Real Quoting',
    status: 'IDLE',
    confidence: 94.3,
    lastAction: 'Matched Miami Ready-Mix Supplier (3.8 miles) @ $165/cu yd',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'COMM-RISK-03',
    name: 'Change-Order Risk Prevention Agent',
    swarmGroup: 'Commercial & Sourcing',
    specialty: 'Trade Clash Detection & Material Lead-Time Risk Mitigation',
    status: 'IDLE',
    confidence: 96.9,
    lastAction: 'Prevented HVAC-to-Plumbing joist penetration clash in Floor 2 deck',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },

  // KNOWLEDGE & JUDGE
  {
    id: 'KNOW-GRAPH-01',
    name: 'Construction Corpus Ingestion Agent',
    swarmGroup: 'Knowledge System',
    specialty: 'FEMA/FBC/IPC Ingestion & Assembly Pattern Extraction',
    status: 'IDLE',
    confidence: 98.1,
    lastAction: 'Ingested FBC 2023 HVHZ Fastener spacing standards',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'JUDGE-FINAL-01',
    name: 'Final Project Construction Judge Agent',
    swarmGroup: 'Independent Verification',
    specialty: 'Holistic Constructability, Code Compliance & Score Certification',
    status: 'IDLE',
    confidence: 99.6,
    lastAction: 'Certified Tampa Residence project score @ 92.4 / 100',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
];
