import { SwarmAgentEntity } from '../src/types/hermes';

export const INITIAL_SWARM_AGENTS: SwarmAgentEntity[] = [
  {
    id: 'PRIME-ORCHESTRATOR-01',
    name: 'HERMES Prime Orchestrator',
    swarmGroup: 'Executive Control',
    specialty: 'Autonomous System Supervision & Gym Curriculum Control',
    status: 'RUNNING',
    confidence: 99.4,
    lastAction: 'Evaluating system skill gaps & scheduling next gym task',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'SITE-AGENT-03',
    name: 'Site Environment & Hydrology Swarm Agent',
    swarmGroup: 'Environmental & Civil',
    specialty: 'Topography, Flood Zones, Soil Bearing & Stormwater Drainage',
    status: 'IDLE',
    confidence: 95.8,
    lastAction: 'Calculated 2,500 PSF allowable soil bearing pressure & VE flood clearance',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'STRUCTURAL-AGENT-01',
    name: 'Structural Concrete & Steel Engineering Agent',
    swarmGroup: 'Structural Engineering',
    specialty: 'Helical Pile Footings, Shear Wall Wind Loads & Rebar Embedment',
    status: 'IDLE',
    confidence: 96.2,
    lastAction: 'Validated ACI 318 5000 PSI concrete & SS316 anchor bolt spacing',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'PLUMBING-AGENT-07',
    name: 'IPC Hydraulic & Drainage Plumbing Agent',
    swarmGroup: 'MEP Services',
    specialty: 'Sanitary Waste Slope, Riser Hydraulic Sizing & Backflow Prevention',
    status: 'IDLE',
    confidence: 94.1,
    lastAction: 'Verified IPC 1/4" per ft gravity drain slope on floor 1',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'HVAC-AGENT-04',
    name: 'Thermal & Air Distribution HVAC Agent',
    swarmGroup: 'MEP Services',
    specialty: 'ASHRAE 90.1 Heat Gain/Loss, HVHZ Duct Static Pressure & Dehumidification',
    status: 'IDLE',
    confidence: 93.7,
    lastAction: 'Calculated 4.5 ton cooling load for Zone 1A high humidity profile',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'ELECTRICAL-AGENT-05',
    name: 'NEC Power & Lighting Electrical Agent',
    swarmGroup: 'MEP Services',
    specialty: 'NEC 2023 Feeder Voltage Drop, GFCI Protection & Panel Calculations',
    status: 'IDLE',
    confidence: 95.0,
    lastAction: 'Balanced 200A 3-phase load schedule & emergency disconnect clearance',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'INSPECTOR-PLUMBING-02',
    name: 'Independent IPC Plumbing Inspector Agent',
    swarmGroup: 'Independent Verification',
    specialty: 'Code Compliance Auditing & Hydraulic Fall Failure Sweeps',
    status: 'IDLE',
    confidence: 98.5,
    lastAction: 'Audited sanitary waste branch line fall compliance',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'INSPECTOR-STRUCTURAL-01',
    name: 'Independent FBC HVHZ Structural Inspector',
    swarmGroup: 'Independent Verification',
    specialty: 'Wind Uplift, Shear Wall Embedment & Coastal Flashing Inspection',
    status: 'IDLE',
    confidence: 98.9,
    lastAction: 'Inspected roof standing seam clip fastener spacing for 175 MPH gust rating',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'REPAIR-AGENT-03',
    name: 'Autonomous Building System Repair Agent',
    swarmGroup: 'Autonomous Correction',
    specialty: 'Parametric Geometry Adjustment, Rebar Respacing & Pipe Re-sloping',
    status: 'IDLE',
    confidence: 97.2,
    lastAction: 'Corrected anchor bolt embedment spacing to 24" o.c. SS316',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'QUANTITY-AGENT-01',
    name: 'Deterministic Quantity Takeoff Engine Agent',
    swarmGroup: 'Quantity & Sourcing',
    specialty: 'Volumetric & Surface Area Dimensional Extraction from BIM Geometry',
    status: 'IDLE',
    confidence: 99.8,
    lastAction: 'Extracted 52 cu yd 5000 PSI concrete & 1,620 sq ft standing seam metal roof',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'PROCUREMENT-AGENT-04',
    name: 'Local Supply Chain & Pricing Evidence Agent',
    swarmGroup: 'Quantity & Sourcing',
    specialty: 'Geographic Supplier Matching, Real Price Quoting & Lead Time Analysis',
    status: 'IDLE',
    confidence: 92.4,
    lastAction: 'Matched Miami-Dade ready-mix supplier within 4.2 miles radius',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'RISK-AGENT-02',
    name: 'Change Order Risk Prevention Agent',
    swarmGroup: 'Risk & Schedule',
    specialty: 'Trade Clash Detection, Long-Lead Materials & Permitting Delay Prevention',
    status: 'IDLE',
    confidence: 94.6,
    lastAction: 'Mitigated structural-to-MEP penetration clash risk',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
  {
    id: 'KNOWLEDGE-AGENT-01',
    name: 'Construction Pattern & Postmortem Knowledge Agent',
    swarmGroup: 'Knowledge System',
    specialty: 'Extracting Reusable Assemblies & Postmortem Lessons Learned',
    status: 'IDLE',
    confidence: 97.9,
    lastAction: 'Promoted FL-HOT-HUMID-EXTERIOR-WALL-004 assembly to VERIFIED pattern',
    lastActionTime: new Date().toISOString(),
    retryCount: 0,
  },
];
