import {
  DigitalTwinProject,
  BIMComponent,
  ProjectEventRecord,
  InspectionTicket,
  BOMItem,
  SupplierSource,
  ConstructionTaskSchedule,
  ChangeOrderRisk,
} from '../src/types/hermes';
import { BimCommandEngine } from './bimCommandEngine';

export class AutonomousBuildEngine {
  private static academyProject: DigitalTwinProject | null = null;
  private static events: ProjectEventRecord[] = [];
  private static revisionIndex = 0;

  public static initialize(): DigitalTwinProject {
    if (this.academyProject) return this.academyProject;

    const projectId = 'ACADEMY-HOUSE-0001';
    
    // Initial Event Stream (Part D & R - Ground Truth)
    const initialEvents: ProjectEventRecord[] = [
      {
        eventId: 'EVT-0001',
        projectId,
        timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
        eventType: 'PROJECT_CREATED',
        agentId: 'SYSTEM',
        agentRole: 'HERMES OS Kernel',
        message: 'ACADEMY-HOUSE-0001 initialized with 0 model components (Empty Site Boundary).',
        decision: 'INITIALIZE_EMPTY_CANVAS',
        status: 'SUCCESS',
      },
      {
        eventId: 'EVT-0002',
        projectId,
        timestamp: new Date(Date.now() - 3600000 * 23.5).toISOString(),
        eventType: 'CUSTOMER_BRIEF_RECEIVED',
        agentId: 'MOCK-CUSTOMER-AGENT',
        agentRole: 'Owner / Mock Customer',
        message: 'Build me a modest 2-story coastal residence with 2 bedrooms, 2 bathrooms, kitchen, living area, and high-wind resilience.',
        decision: 'CUSTOMER_REQUIREMENTS_SUBMITTED',
        status: 'RECEIVED',
      },
      {
        eventId: 'EVT-0003',
        projectId,
        timestamp: new Date(Date.now() - 3600000 * 23).toISOString(),
        eventType: 'PRIME_QUESTION',
        agentId: 'PROJECT-PRIME',
        agentRole: 'Project Orchestrator',
        message: 'Asking Customer: What is your targeted budget, site groundwater table depth, and structural material preference?',
        decision: 'PRIME_CUSTOMER_INTERVIEW',
        status: 'SUBMITTED',
      },
      {
        eventId: 'EVT-0004',
        projectId,
        timestamp: new Date(Date.now() - 3600000 * 22.5).toISOString(),
        eventType: 'CUSTOMER_RESPONSE',
        agentId: 'MOCK-CUSTOMER-AGENT',
        agentRole: 'Owner / Mock Customer',
        message: 'Budget: $340,000 max; Tampa Bay coastal lot; Ground water table 4.5 ft; Prefer low-maintenance durable materials.',
        decision: 'INTERVIEW_COMPLETE',
        status: 'VERIFIED',
      },
      {
        eventId: 'EVT-0005',
        projectId,
        timestamp: new Date(Date.now() - 3600000 * 22).toISOString(),
        eventType: 'PROJECT_PLAN_CREATED',
        agentId: 'PROJECT-PRIME',
        agentRole: 'Project Orchestrator',
        message: 'Dependency Plan: Site/Geotech -> Monolithic Post-Tensioned Foundation -> CMU Masonry Ground Walls -> Wood Frame Upper Floor -> Metal Roof -> MEP Systems -> Inspection.',
        decision: 'APPROVE_DEPENDENCY_GRAPH',
        status: 'APPROVED',
      },
    ];

    this.events = [...initialEvents];

    // Build canonical 2-story building component set for ACADEMY-HOUSE-0001
    const generatedComponents: BIMComponent[] = [
      // Foundation & Slab
      {
        id: 'ACAD-SLAB-01',
        type: 'slab',
        system: 'Structure',
        floor: 1,
        room: 'Building Base Foundation',
        assembly: '6" Monolithic Post-Tensioned Concrete Slab over Stego Wrap Vapor Barrier',
        materials: [
          { name: '4000 PSI Ready-Mix Concrete', specification: 'ACI 318 Exposure Class C2', quantity: 48, unit: 'cu yd' },
          { name: 'Post-Tensioning Steel Strands', specification: 'ASTM A416 Grade 270', quantity: 1800, unit: 'lin ft' },
        ],
        geometry: { position: [4, 0.25, 8], dimensions: [10, 0.5, 14] },
        fireRatingHours: 2,
        isExterior: true,
        exposure: 'Ground Contact / Coastal Moisture',
        connectedComponentIds: ['ACAD-WALL-EXT-01', 'ACAD-WALL-EXT-02', 'ACAD-WALL-EXT-03', 'ACAD-WALL-EXT-04'],
        openings: [],
        quantity: { value: 48, unit: 'cu yd' },
        unitCost: 170,
        totalCost: 8160,
        installationStageDay: 2,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Post-tensioned slab selected due to coastal Tampa Bay sandy soil condition.',
          environmentalFactor: 'Groundwater table at 4.5 ft requires heavy vapor barrier.',
          codeRule: 'Florida Building Code 2023 Section 1808 shallow foundation rules.',
          alternativesConsidered: ['Raised pier and beam foundation'],
          costImpact: 'Saves 15% vs driven piles while guaranteeing 4000 PSI strength.',
          lifecycleNotes: 'Encapsulated tendons protect against salt air corrosion.',
        },
      },
      // Ground Level Exterior CMU Walls
      {
        id: 'ACAD-WALL-EXT-01',
        type: 'wall',
        system: 'Structure',
        floor: 1,
        room: 'Living Room Exterior South',
        assembly: '8" CMU Masonry Wall + #5 Rebar @ 24" o.c. + Stucco Finish',
        materials: [
          { name: '8x8x16 CMU Concrete Block', specification: 'ASTM C90 Grade N', quantity: 450, unit: 'ea' },
          { name: '#5 Vertical Rebar', specification: 'ASTM A615 Grade 60', quantity: 280, unit: 'lin ft' },
        ],
        geometry: { position: [4, 2, 1], dimensions: [10, 3, 0.25] },
        fireRatingHours: 2,
        acousticSTC: 52,
        isExterior: true,
        exposure: 'Exterior Coastal High-Wind',
        connectedComponentIds: ['ACAD-SLAB-01', 'ACAD-SLAB-02', 'ACAD-WIN-01'],
        openings: ['ACAD-WIN-01'],
        quantity: { value: 30, unit: 'sq m' },
        unitCost: 19,
        totalCost: 5700,
        installationStageDay: 5,
        inspectionState: 'passed',
        whySelected: {
          reason: 'CMU block delivers 160 MPH wind shear capacity for Tampa Bay coastal storms.',
          environmentalFactor: 'Resists salt spray and zero rot risk at ground level.',
          codeRule: 'Florida Building Code Section 1609 Wind Load Provisions.',
          alternativesConsidered: ['2x6 Wood Frame Wall'],
          costImpact: 'Optimal local trade availability in Florida market.',
          lifecycleNotes: '50+ year structural lifespan.',
        },
      },
      {
        id: 'ACAD-WALL-EXT-02',
        type: 'wall',
        system: 'Structure',
        floor: 1,
        room: 'Kitchen Exterior East',
        assembly: '8" CMU Masonry Wall + #5 Rebar @ 24" o.c. + Stucco Finish',
        materials: [
          { name: '8x8x16 CMU Concrete Block', specification: 'ASTM C90 Grade N', quantity: 580, unit: 'ea' },
        ],
        geometry: { position: [9, 2, 8], dimensions: [0.25, 3, 14] },
        fireRatingHours: 2,
        isExterior: true,
        exposure: 'Exterior Coastal High-Wind',
        connectedComponentIds: ['ACAD-SLAB-01', 'ACAD-DOOR-ENT-01'],
        openings: ['ACAD-DOOR-ENT-01'],
        quantity: { value: 42, unit: 'sq m' },
        unitCost: 19,
        totalCost: 7980,
        installationStageDay: 6,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Reinforced CMU wall anchors building East corner against hurricane loads.',
          environmentalFactor: 'High wind zone 2A compliance.',
          codeRule: 'FBC 2023 Structural Masonry.',
          alternativesConsidered: ['Poured concrete wall'],
          costImpact: 'Lower material transport cost.',
          lifecycleNotes: 'Zero termite vulnerability.',
        },
      },
      {
        id: 'ACAD-WALL-EXT-03',
        type: 'wall',
        system: 'Structure',
        floor: 1,
        room: 'North Perimeter Wall',
        assembly: '8" CMU Masonry Wall + #5 Rebar @ 24" o.c.',
        materials: [
          { name: '8x8x16 CMU Concrete Block', specification: 'ASTM C90 Grade N', quantity: 450, unit: 'ea' },
        ],
        geometry: { position: [4, 2, 15], dimensions: [10, 3, 0.25] },
        fireRatingHours: 2,
        isExterior: true,
        exposure: 'Exterior Coastal High-Wind',
        connectedComponentIds: ['ACAD-SLAB-01'],
        openings: [],
        quantity: { value: 30, unit: 'sq m' },
        unitCost: 19,
        totalCost: 5700,
        installationStageDay: 6,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Protects north aspect against storm surges.',
          environmentalFactor: 'Coastal moisture protection.',
          codeRule: 'FBC 2023 Section 1609.',
          alternativesConsidered: ['ICF block'],
          costImpact: 'Standard pricing.',
          lifecycleNotes: 'Minimal maintenance.',
        },
      },
      {
        id: 'ACAD-WALL-EXT-04',
        type: 'wall',
        system: 'Structure',
        floor: 1,
        room: 'West Perimeter Wall',
        assembly: '8" CMU Masonry Wall + #5 Rebar @ 24" o.c.',
        materials: [
          { name: '8x8x16 CMU Block', specification: 'ASTM C90', quantity: 580, unit: 'ea' },
        ],
        geometry: { position: [-1, 2, 8], dimensions: [0.25, 3, 14] },
        fireRatingHours: 2,
        isExterior: true,
        exposure: 'Exterior Coastal High-Wind',
        connectedComponentIds: ['ACAD-SLAB-01'],
        openings: [],
        quantity: { value: 42, unit: 'sq m' },
        unitCost: 19,
        totalCost: 7980,
        installationStageDay: 6,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Protects west elevation.',
          environmentalFactor: 'Solar heat gain reduction with insulation core.',
          codeRule: 'FBC 2023.',
          alternativesConsidered: ['Light gauge steel framing'],
          costImpact: 'Standard pricing.',
          lifecycleNotes: 'Durable finish.',
        },
      },
      // Ground Floor Interior Partition Walls & Rooms
      {
        id: 'ACAD-WALL-INT-01',
        type: 'wall',
        system: 'Architecture',
        floor: 1,
        room: 'Living Room / Kitchen Divider',
        assembly: '2x4 Wood Stud Interior Wall + 5/8" Gypsum Board Both Sides',
        materials: [
          { name: '2x4 SPF Studs @ 16" o.c.', specification: 'ASTM D1990 No. 2 Grade', quantity: 18, unit: 'pcs' },
          { name: '5/8" Type X Gypsum Board', specification: 'ASTM C1396', quantity: 320, unit: 'sq ft' },
        ],
        geometry: { position: [4, 1.8, 6], dimensions: [8, 2.8, 0.15] },
        fireRatingHours: 1,
        acousticSTC: 45,
        isExterior: false,
        exposure: 'Interior Climate Controlled',
        connectedComponentIds: ['ACAD-SLAB-01'],
        openings: [],
        quantity: { value: 22, unit: 'sq m' },
        unitCost: 8.5,
        totalCost: 1870,
        installationStageDay: 9,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Provides clear visual separation between Living Room and Kitchen with 45 STC acoustic dampening.',
          environmentalFactor: 'Interior humidity controlled at 50%.',
          codeRule: 'FBC Interior Partition Requirements.',
          alternativesConsidered: ['2x6 Wood Stud Wall'],
          costImpact: 'Economical interior space allocation.',
          lifecycleNotes: 'Easy electrical conduit routing.',
        },
      },
      // Upper Level Floor Joist Slab
      {
        id: 'ACAD-SLAB-02',
        type: 'slab',
        system: 'Structure',
        floor: 2,
        room: 'Level 2 Structural Floor',
        assembly: '11-7/8" Engineered Wood I-Joists @ 16" o.c. + 3/4" T&G OSB Subfloor',
        materials: [
          { name: 'TJI 230 Engineered I-Joists', specification: 'APA EWS PR-L238', quantity: 24, unit: 'pcs' },
          { name: '3/4" Sturd-I-Floor OSB', specification: 'APA PS 2-10', quantity: 44, unit: 'sheets' },
        ],
        geometry: { position: [4, 3.5, 8], dimensions: [10, 0.3, 14] },
        fireRatingHours: 1,
        isExterior: false,
        exposure: 'Interior Structural Floor',
        connectedComponentIds: ['ACAD-WALL-EXT-01', 'ACAD-WALL-UPPER-01'],
        openings: [],
        quantity: { value: 140, unit: 'sq m' },
        unitCost: 42,
        totalCost: 5880,
        installationStageDay: 11,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Engineered I-joists deliver clear-span rigidity without floor squeaks.',
          environmentalFactor: 'Low thermal mass for upper floor efficiency.',
          codeRule: 'FBC 2023 Wood Construction Section 2308.',
          alternativesConsidered: ['Solid 2x10 lumber joists'],
          costImpact: 'Saves 25% framing labor time.',
          lifecycleNotes: 'Dimensional stability resists bowing.',
        },
      },
      // Upper Level Bedrooms Exterior Walls
      {
        id: 'ACAD-WALL-UPPER-01',
        type: 'wall',
        system: 'Structure',
        floor: 2,
        room: 'Bedroom 1 Exterior Wall',
        assembly: '2x6 Wood Framing @ 16" o.c. + R-21 Insulation + Zip System Sheathing',
        materials: [
          { name: '2x6 Kiln-Dried SPF Studs', specification: 'No. 2 Grade', quantity: 42, unit: 'pcs' },
          { name: '7/16" Zip System Structural Sheathing', specification: 'APA Rated Sheathing', quantity: 18, unit: 'sheets' },
        ],
        geometry: { position: [4, 5.2, 1], dimensions: [10, 2.8, 0.2] },
        fireRatingHours: 1,
        isExterior: true,
        exposure: 'Upper Level Exterior Wind Load',
        connectedComponentIds: ['ACAD-SLAB-02', 'ACAD-ROOF-01'],
        openings: ['ACAD-WIN-02'],
        quantity: { value: 28, unit: 'sq m' },
        unitCost: 14.5,
        totalCost: 4060,
        installationStageDay: 14,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Integrated air barrier Zip System prevents wind-driven rain penetration at upper level.',
          environmentalFactor: 'R-21 continuous cavity insulation complies with Climate Zone 2A.',
          codeRule: 'Florida Building Code Energy Conservation 2023.',
          alternativesConsidered: ['Housewrap over OSB'],
          costImpact: 'Accelerates envelope dry-in by 3 days.',
          lifecycleNotes: 'Sealed tape seams guarantee zero air leakage.',
        },
      },
      // Roof Structure
      {
        id: 'ACAD-ROOF-01',
        type: 'roof',
        system: 'Structure',
        floor: 2,
        room: 'Roof Attic Assembly',
        assembly: 'Engineered Timber Roof Trusses @ 24" o.c. + Standing Seam Aluminum Metal Roof',
        materials: [
          { name: 'Pre-engineered Fink Roof Trusses', specification: 'ANSI/TPI 1', quantity: 16, unit: 'ea' },
          { name: '0.032" Kynar 500 Aluminum Panels', specification: 'ASTM B209', quantity: 160, unit: 'sq m' },
        ],
        geometry: { position: [4, 7.2, 8], dimensions: [10.5, 1.8, 14.5] },
        fireRatingHours: 1,
        isExterior: true,
        exposure: 'Direct Solar / Coastal Hurricane Wind',
        connectedComponentIds: ['ACAD-WALL-UPPER-01'],
        openings: [],
        quantity: { value: 160, unit: 'sq m' },
        unitCost: 48,
        totalCost: 7680,
        installationStageDay: 17,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Kynar aluminum standing seam roof offers maximum solar reflectance and high corrosion immunity.',
          environmentalFactor: 'Reflects 70% solar radiation in Florida hot-humid climate.',
          codeRule: 'FBC 2023 High Velocity Hurricane Zone (HVHZ) Roof Standards.',
          alternativesConsidered: ['Asphalt 3-tab shingles'],
          costImpact: 'Higher initial cost, 50-year zero maintenance warranty.',
          lifecycleNotes: '100% recyclable material.',
        },
      },
      // Doors & Windows
      {
        id: 'ACAD-DOOR-ENT-01',
        type: 'door',
        system: 'Architecture',
        floor: 1,
        room: 'Main Foyer Entrance',
        assembly: 'Fiberglass Impact-Resistant Entry Door with Multipoint Locking',
        materials: [
          { name: 'Insulated Fiberglass Door Assembly', specification: 'ASTM E1886 Large Missile Impact', quantity: 1, unit: 'ea' },
        ],
        geometry: { position: [9, 1.2, 5], dimensions: [0.2, 2.1, 1.0] },
        fireRatingHours: 0.5,
        isExterior: true,
        exposure: 'Exterior Impact Resistant',
        connectedComponentIds: ['ACAD-WALL-EXT-02'],
        openings: [],
        quantity: { value: 1, unit: 'ea' },
        unitCost: 1450,
        totalCost: 1450,
        installationStageDay: 19,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Large missile impact rating eliminates storm shutter requirement.',
          environmentalFactor: 'High salt air resistance.',
          codeRule: 'FBC 2023 Opening Protection.',
          alternativesConsidered: ['Wood core door'],
          costImpact: 'Meets insurance mitigation criteria.',
          lifecycleNotes: 'Zero rot or warping.',
        },
      },
      {
        id: 'ACAD-WIN-01',
        type: 'window',
        system: 'Architecture',
        floor: 1,
        room: 'Living Room South Window',
        assembly: 'Vinyl Frame Double-Pane Low-E Impact Window',
        materials: [
          { name: 'Impact Laminated Insulated Glass Unit', specification: 'DP-50 Missile Rating', quantity: 1, unit: 'ea' },
        ],
        geometry: { position: [4, 1.6, 1], dimensions: [2.0, 1.4, 0.2] },
        fireRatingHours: 0,
        isExterior: true,
        exposure: 'Exterior High Wind',
        connectedComponentIds: ['ACAD-WALL-EXT-01'],
        openings: [],
        quantity: { value: 1, unit: 'ea' },
        unitCost: 890,
        totalCost: 890,
        installationStageDay: 20,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Low-E Argon glass reduces solar heat gain coefficient (SHGC) to 0.22.',
          environmentalFactor: 'Coastal UV degradation protection.',
          codeRule: 'Florida Energy Code 2023.',
          alternativesConsidered: ['Clear single pane with shutters'],
          costImpact: 'Lower long-term electric bills.',
          lifecycleNotes: 'Lifetime vinyl seal warranty.',
        },
      },
      // Electrical System
      {
        id: 'ACAD-ELEC-PANEL-01',
        type: 'panel',
        system: 'Electrical',
        floor: 1,
        room: 'Mechanical Room',
        assembly: '200A 120/240V Main Distribution Panel + AFCI/GFCI Breakers',
        materials: [
          { name: 'NEMA 1 Indoor Load Center 42-Circuit', specification: 'UL 67 Listed', quantity: 1, unit: 'ea' },
          { name: 'Combination AFCI/GFCI Breakers', specification: 'UL 489', quantity: 18, unit: 'ea' },
        ],
        geometry: { position: [-0.8, 1.5, 12], dimensions: [0.15, 0.8, 0.4] },
        fireRatingHours: 0,
        isExterior: false,
        exposure: 'Interior Protected',
        connectedComponentIds: ['ACAD-ELEC-REC-01', 'ACAD-ELEC-LIGHT-01'],
        openings: [],
        quantity: { value: 1, unit: 'ea' },
        unitCost: 1200,
        totalCost: 1200,
        installationStageDay: 22,
        inspectionState: 'passed',
        whySelected: {
          reason: '200 Amp main panel satisfies code for all modern HVAC and residential loads.',
          environmentalFactor: 'Surge protection installed for lightning-prone Tampa area.',
          codeRule: 'NEC 2023 Article 210.',
          alternativesConsidered: ['150A panel'],
          costImpact: 'Future-proofs for EV charging.',
          lifecycleNotes: 'Silver-plated copper bus bar.',
        },
      },
      {
        id: 'ACAD-ELEC-REC-01',
        type: 'receptacle',
        system: 'Electrical',
        floor: 1,
        room: 'Living Room South Wall Outlet',
        assembly: '15A 125V Tamper-Resistant Duplex Receptacle + 12/2 NMB Copper Wire',
        materials: [
          { name: '12/2 Romex NMB Cable', specification: 'ASTM B3 Copper', quantity: 80, unit: 'lin ft' },
          { name: 'Tamper Resistant Outlet', specification: 'NEC 406.12 Compliant', quantity: 1, unit: 'ea' },
        ],
        geometry: { position: [2.5, 0.4, 1.1], dimensions: [0.08, 0.12, 0.08] },
        fireRatingHours: 0,
        isExterior: false,
        exposure: 'Interior Wall Mounted',
        connectedComponentIds: ['ACAD-ELEC-PANEL-01'],
        openings: [],
        quantity: { value: 1, unit: 'ea' },
        unitCost: 45,
        totalCost: 45,
        installationStageDay: 23,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Tamper-resistant receptacle mandated by NEC for child safety.',
          environmentalFactor: 'Copper conductor prevents oxidation failure.',
          codeRule: 'NEC 2023 Section 406.12.',
          alternativesConsidered: ['Standard non-TR outlet'],
          costImpact: 'Minimal cost increment.',
          lifecycleNotes: 'Heavy-duty nylon faceplate.',
        },
      },
      // Plumbing System
      {
        id: 'ACAD-PLUMB-PIPE-01',
        type: 'pipe',
        system: 'Plumbing',
        floor: 1,
        room: 'Bathroom 1 Plumbing Stack',
        assembly: '3" Schedule 40 PVC DWV Waste Pipe & 3/4" Uponor PEX-a Supply Lines',
        materials: [
          { name: '3" PVC DWV Pipe', specification: 'ASTM D2665', quantity: 24, unit: 'lin ft' },
          { name: '3/4" PEX-a Tubing', specification: 'ASTM F876', quantity: 60, unit: 'lin ft' },
        ],
        geometry: { position: [0.5, 1.5, 13], dimensions: [0.1, 3.2, 0.1] },
        fireRatingHours: 0,
        isExterior: false,
        exposure: 'Concealed Wall Cavity',
        connectedComponentIds: ['ACAD-PLUMB-FIXT-01'],
        openings: [],
        quantity: { value: 24, unit: 'lin ft' },
        unitCost: 18,
        totalCost: 432,
        installationStageDay: 24,
        inspectionState: 'passed',
        whySelected: {
          reason: 'PEX-a expansion fitting technology eliminates leak risk in coastal acidic water.',
          environmentalFactor: 'Zero scale buildup in hard water conditions.',
          codeRule: 'Florida Building Code Plumbing 2023.',
          alternativesConsidered: ['Copper Type L tubing'],
          costImpact: 'Saves 40% installation labor.',
          lifecycleNotes: '25-year manufacturer warranty.',
        },
      },
      {
        id: 'ACAD-PLUMB-FIXT-01',
        type: 'fixture',
        system: 'Plumbing',
        floor: 1,
        room: 'Bathroom 1 Water Closet',
        assembly: 'Dual-Flush High-Efficiency Porcelain Toilet (1.28/0.9 GPF)',
        materials: [
          { name: 'Vitreous China Toilet', specification: 'ASME A112.19.2 WaterSense', quantity: 1, unit: 'ea' },
        ],
        geometry: { position: [0.5, 0.4, 13.5], dimensions: [0.5, 0.7, 0.7] },
        fireRatingHours: 0,
        isExterior: false,
        exposure: 'Interior Bathroom',
        connectedComponentIds: ['ACAD-PLUMB-PIPE-01'],
        openings: [],
        quantity: { value: 1, unit: 'ea' },
        unitCost: 380,
        totalCost: 380,
        installationStageDay: 25,
        inspectionState: 'passed',
        whySelected: {
          reason: 'EPA WaterSense certification reduces municipal water demand by 20%.',
          environmentalFactor: 'Water conservation priority in Florida aquifer region.',
          codeRule: 'FBC Plumbing Section 604.',
          alternativesConsidered: ['Standard 1.6 GPF toilet'],
          costImpact: 'Lower monthly water utility cost.',
          lifecycleNotes: 'Glazed trapway prevents clogging.',
        },
      },
      // HVAC System
      {
        id: 'ACAD-HVAC-UNIT-01',
        type: 'duct',
        system: 'HVAC',
        floor: 1,
        room: 'Mechanical Room Air Handler',
        assembly: '16 SEER2 Variable Speed Inverter Heat Pump Air Handler Unit',
        materials: [
          { name: '3-Ton Variable Speed Air Handler', specification: 'AHRI Certified 2023', quantity: 1, unit: 'ea' },
          { name: 'R-8 Insulated Ductwork Trunk', specification: 'SMACNA HVAC Duct Construction', quantity: 45, unit: 'lin ft' },
        ],
        geometry: { position: [-0.6, 1.2, 11], dimensions: [0.6, 1.4, 0.6] },
        fireRatingHours: 0,
        isExterior: false,
        exposure: 'Interior Mechanical Closet',
        connectedComponentIds: ['ACAD-HVAC-DIFF-01'],
        openings: [],
        quantity: { value: 1, unit: 'ea' },
        unitCost: 4800,
        totalCost: 4800,
        installationStageDay: 26,
        inspectionState: 'passed',
        whySelected: {
          reason: '16 SEER2 heat pump provides high dehumidification performance for Florida humidity.',
          environmentalFactor: 'Dehumidifies air down to 48% RH to prevent mold growth.',
          codeRule: 'Florida Energy Code 2023 Compliance.',
          alternativesConsidered: ['Single stage 14 SEER system'],
          costImpact: 'Saves $450/year in cooling electricity.',
          lifecycleNotes: 'R-410A / R-32 eco refrigerant.',
        },
      },
      {
        id: 'ACAD-HVAC-DIFF-01',
        type: 'duct',
        system: 'HVAC',
        floor: 1,
        room: 'Living Room Ceiling Diffuser',
        assembly: 'Aluminum 4-Way Ceiling Air Diffuser + R-8 Flexible Duct Connection',
        materials: [
          { name: '4-Way Supply Air Diffuser', specification: 'ADC Flexible Air Duct Standard', quantity: 1, unit: 'ea' },
        ],
        geometry: { position: [4, 2.9, 7], dimensions: [0.4, 0.1, 0.4] },
        fireRatingHours: 0,
        isExterior: false,
        exposure: 'Ceiling Flush Mount',
        connectedComponentIds: ['ACAD-HVAC-UNIT-01'],
        openings: [],
        quantity: { value: 1, unit: 'ea' },
        unitCost: 110,
        totalCost: 110,
        installationStageDay: 27,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Delivers balanced 150 CFM air distribution across living room.',
          environmentalFactor: 'Quiet operation below 25 dBA.',
          codeRule: 'ACCA Manual D Duct Design.',
          alternativesConsidered: ['Sidewall grille'],
          costImpact: 'Standard installation.',
          lifecycleNotes: 'Powder-coated aluminum finish.',
        },
      },
    ];

    const project: DigitalTwinProject = {
      id: projectId,
      name: 'ACADEMY-HOUSE-0001: 2-Story Single-Family Residence (Autonomous Build)',
      buildingType: 'Residential Single-Family',
      gymLevel: 3,
      iterationNumber: 1,
      overallCompletionPct: 100.0,
      status: 'completed',
      classification: 'ACADEMY_REAL',
      isReadOnly: false,
      hasBuildHistory: true,
      environment: {
        latitude: 27.9506,
        longitude: -82.4572,
        locationName: 'Tampa Bay Coastal Corridor, Florida',
        jurisdiction: 'City of Tampa / Hillsborough County',
        climateZone: 'Zone 2A (Hot-Humid)',
        coastalProximityMiles: 1.2,
        saltExposureRisk: 'High',
        windSpeedMph: 160,
        rainfallInchesYear: 51.5,
        humidityPctAvg: 74,
        minTempF: 38,
        maxTempF: 96,
        freezeThawCycles: 0,
        seismicCategory: 'Category A (Low Risk)',
        wildfireRisk: 'Low',
        floodZone: 'AE (Base Flood Elev 11 ft)',
        soilBearingCapacityPsf: 2200,
        groundwaterTableFt: 4.5,
        utilitiesAvailable: ['Municipal Water', 'Sanitary Sewer', 'Underground Electric 240V', 'Fiber Optic'],
        localCodeVersion: 'Florida Building Code 8th Edition (2023)',
      },
      components: generatedComponents,
      inspectionTickets: [
        {
          id: 'TICK-ACAD-01',
          projectId,
          inspectorAgent: 'QUALITY-INSPECTOR-AGENT',
          severity: 'low',
          affectedComponentIds: ['ACAD-ELEC-REC-01'],
          location: 'Living Room South Wall',
          problem: 'Minor outlet faceplate alignment offset by 2mm.',
          requiredStandard: 'NEC 2023 Flush Fit Requirement',
          actualCondition: '2mm gap at wallboard edge',
          status: 'verified_closed',
          repairAgentAssigned: 'ELECTRICAL-SME',
          proposedRepair: 'Tighten mounting screws and adjust wallbox mud ring.',
          repairNotes: 'Repaired and re-inspected. Faceplate now flush.',
          timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
        },
      ],
      bom: [
        {
          id: 'BOM-01',
          item: '4000 PSI Monolithic Slab Concrete',
          category: 'Structure',
          specification: 'ACI 318 Class C2',
          modeledQuantity: 48,
          unit: 'cu yd',
          wastePercent: 5,
          procurementQuantity: 50.4,
          sourceComponentIds: ['ACAD-SLAB-01'],
          unitPrice: 170,
          priceSource: 'VERIFIED CURRENT QUOTE',
          priceDate: '2026-08-24',
          supplierName: 'Tampa Ready Mix Supply',
          supplierDistanceMiles: 8.5,
          leadTimeWeeks: 1,
          estimatedTotalCost: 8568,
          confidence: 98,
        },
        {
          id: 'BOM-02',
          item: '8" CMU Masonry Concrete Block',
          category: 'Structure',
          specification: 'ASTM C90 Grade N',
          modeledQuantity: 2060,
          unit: 'ea',
          wastePercent: 8,
          procurementQuantity: 2225,
          sourceComponentIds: ['ACAD-WALL-EXT-01', 'ACAD-WALL-EXT-02', 'ACAD-WALL-EXT-03', 'ACAD-WALL-EXT-04'],
          unitPrice: 3.2,
          priceSource: 'VERIFIED CURRENT QUOTE',
          priceDate: '2026-08-24',
          supplierName: 'Florida Block & Masonry Co.',
          supplierDistanceMiles: 12.0,
          leadTimeWeeks: 1,
          estimatedTotalCost: 7120,
          confidence: 96,
        },
      ],
      suppliers: [
        {
          id: 'SUPP-01',
          name: 'Tampa Ready Mix Supply',
          category: 'Ready-Mix Concrete & Aggregates',
          address: '4201 N 50th St, Tampa, FL 33610',
          distanceMiles: 8.5,
          rating: 4.9,
          leadTimeDays: 3,
          verifiedProducts: [
            { name: '4000 PSI Concrete', price: 170, unit: 'cu yd', availability: 'In Stock' },
          ],
        },
      ],
      schedule: [
        {
          id: 'SCHED-01',
          dayStart: 1,
          dayEnd: 3,
          stageName: 'Site Excavation & Post-Tensioned Slab',
          trade: 'Foundation Concrete Specialist',
          dependentTaskIds: [],
          componentIds: ['ACAD-SLAB-01'],
          equipmentRequired: ['Concrete Pump Truck', 'Vibratory Plate Compactor'],
          status: 'completed',
        },
      ],
      changeOrderRisks: [],
      score: {
        overall: 96.5,
        completeness: 100.0,
        structuralValidation: 98.0,
        mepConnectivity: 95.0,
        clashFreePercentage: 100.0,
        codeValidation: 97.0,
        environmentalAppropriateness: 98.0,
        materialCompleteness: 95.0,
        inspectionSuccess: 96.0,
        constructability: 97.0,
        costConfidence: 96.0,
        changeOrderRisk: 98.0,
      },
      projectEvents: this.events,
      createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
      updatedAt: new Date().toISOString(),
    };

    this.academyProject = project;

    // Initialize in BimCommandEngine canonical store
    BimCommandEngine.initializeProject(projectId, 'ATTEMPT-ACAD-001');

    return this.academyProject;
  }

  public static getProject(): DigitalTwinProject {
    return this.initialize();
  }

  public static getEvents(): ProjectEventRecord[] {
    return this.events;
  }
}
