import { DigitalTwinProject, KnowledgeEntity, LearnedLesson } from '../src/types/hermes';
import { generateBOMFromComponents } from './deterministicGeometryEngine';

export const INITIAL_SEED_PROJECTS: DigitalTwinProject[] = [
  {
    id: 'RESIDENCE-TAMPA-001',
    name: 'House #1: Tampa Coastal 2-Story Residence',
    buildingType: 'Residential Single-Family',
    gymLevel: 3,
    iterationNumber: 1,
    overallCompletionPct: 85.0,
    status: 'inspecting',
    environment: {
      latitude: 27.9506,
      longitude: -82.4572,
      locationName: 'Tampa Bay Coastal Corridor, Florida',
      jurisdiction: 'City of Tampa / Hillsborough County',
      climateZone: 'Zone 2A (Hot-Humid)',
      coastalProximityMiles: 1.2,
      saltExposureRisk: 'High',
      windSpeedMph: 160,
      rainfallInchesYear: 51.5,
      humidityPctAvg: 74,
      minTempF: 38,
      maxTempF: 96,
      freezeThawCycles: 0,
      seismicCategory: 'Category A (Low Risk)',
      wildfireRisk: 'Low',
      floodZone: 'AE (Base Flood Elev 11 ft)',
      soilBearingCapacityPsf: 2200,
      groundwaterTableFt: 4.5,
      utilitiesAvailable: ['Municipal Water', 'Sanitary Sewer', 'Underground Electric 240V', 'Fiber Optic'],
      localCodeVersion: 'Florida Building Code 8th Edition (2023)',
    },
    components: [
      {
        id: 'SLAB-1-001',
        type: 'slab',
        system: 'Structure',
        floor: 1,
        room: 'Building Base Foundation',
        assembly: '6" Monolithic Post-Tensioned Concrete Slab over 15 mil Stego Wrap Vapor Barrier & 4" Clean Gravel',
        materials: [
          { name: '4000 PSI Ready-Mix Concrete', specification: 'ACI 318 Exposure Class C2 (Chloride Exposure)', quantity: 52, unit: 'cu yd' },
          { name: '1/2" Post-Tensioning Steel Strands', specification: 'ASTM A416 Grade 270 Unbonded', quantity: 2100, unit: 'lin ft' },
          { name: '#5 Rebar Perimeter Stem Wall', specification: 'ASTM A615 Grade 60', quantity: 980, unit: 'lin ft' },
        ],
        geometry: { position: [0, 0, 0], dimensions: [44, 0.5, 34] },
        fireRatingHours: 2,
        isExterior: true,
        exposure: 'Ground Contact / Moisture Risk',
        connectedComponentIds: ['WALL-1-101', 'FOOTING-1-001'],
        openings: [],
        quantity: { value: 52, unit: 'cu yd' },
        unitCost: 165,
        totalCost: 8580,
        installationStageDay: 3,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Post-tensioned monolithic slab resists soil settlement on sandy coastal Florida soil.',
          environmentalFactor: 'Groundwater table at 4.5 ft requires 15 mil heavy vapor barrier to eliminate capillary moisture drive.',
          codeRule: 'Florida Building Code Section 1808 shallow foundation requirements.',
          alternativesConsidered: ['Stem wall with raised wood floor', 'Deep driven concrete piles'],
          costImpact: 'Saves 18% cost vs deep piling while maintaining structural load integrity.',
          lifecycleNotes: 'Zero corrosion risk when post-tension tendons are grease-encapsulated.',
        },
      },
      {
        id: 'WALL-1-EXT-01',
        type: 'wall',
        system: 'Structure',
        floor: 1,
        room: 'Level 1 Exterior Perimeter',
        assembly: '8" CMU Block Masonry + Rebar Reinforced Cells @ 24" o.c. + Stucco + 5/8" Type-X Gypsum',
        materials: [
          { name: '8x8x16 CMU Block', specification: 'ASTM C90 Grade N Type 1', quantity: 1550, unit: 'ea' },
          { name: '3000 PSI Masonry Grout Fill', specification: 'ASTM C476 Fine Grout', quantity: 20, unit: 'cu yd' },
          { name: '#5 Vertical Rebar @ 24" o.c.', specification: 'ASTM A615 Grade 60', quantity: 740, unit: 'lin ft' },
        ],
        geometry: { position: [0, 5, -17], dimensions: [44, 10, 0.67] },
        fireRatingHours: 2,
        acousticSTC: 52,
        isExterior: true,
        exposure: 'Exterior Coastal Exposure / 160 MPH Wind',
        connectedComponentIds: ['SLAB-1-001', 'SLAB-2-001'],
        openings: ['WINDOW-1-001', 'DOOR-1-001'],
        quantity: { value: 440, unit: 'sq ft' },
        unitCost: 18.5,
        totalCost: 8140,
        installationStageDay: 8,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Grouted CMU masonry delivers wind resistance against 160 MPH hurricane projectiles.',
          environmentalFactor: 'Salt spray & high humidity destroy unprotected wood exterior framing at ground level.',
          codeRule: 'HVHZ High Velocity Hurricane Zone wall mass requirement.',
          alternativesConsidered: ['2x6 Wood Frame Wall', 'Insulated Concrete Forms (ICF)'],
          costImpact: 'Optimal local labor availability in Florida mason market.',
          lifecycleNotes: '50+ year structural lifespan with zero rot risk.',
        },
      },
      {
        id: 'ROOF-2-001',
        type: 'roof',
        system: 'Envelope',
        floor: 2,
        room: 'Roof System',
        assembly: 'Engineered Wood Hip Truss @ 24" o.c. + 5/8" CDX Deck + Self-Adhered Secondary Water Barrier + 24-Ga Galvalume Standing Seam Metal Panels',
        materials: [
          { name: '24-Ga Galvalume Standing Seam Metal', specification: 'Kynar 500 Finish, 160 MPH Rated', quantity: 1720, unit: 'sq ft' },
          { name: '5/8" CDX Exterior Plywood Sheathing', specification: 'APA Rated Sheathing Exposure 1', quantity: 1720, unit: 'sq ft' },
          { name: 'Self-Adhered Ice & Water Shield WRB', specification: 'ASTM D1970 High Temp Membrane', quantity: 1720, unit: 'sq ft' },
        ],
        geometry: { position: [0, 22, 0], dimensions: [46, 6, 36] },
        fireRatingHours: 1,
        isExterior: true,
        exposure: '160 MPH Wind / Direct Sunlight UV',
        connectedComponentIds: ['WALL-1-EXT-01'],
        openings: [],
        quantity: { value: 1720, unit: 'sq ft' },
        unitCost: 14.2,
        totalCost: 24424,
        installationStageDay: 18,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Hip roof geometry offers maximum aerodynamic resistance against hurricane wind uplift forces.',
          environmentalFactor: 'Galvalume coating resists salt air corrosion superior to standard galvanized steel.',
          codeRule: 'Florida Building Code Section 1507 metal roof uplift load test compliance.',
          alternativesConsidered: ['Architectural Asphalt Shingles', 'Concrete Roof Tile'],
          costImpact: '2.2x cost of asphalt shingle, offset by insurance discount and 40-year durability.',
          lifecycleNotes: 'Reflects 70% solar radiation, drastically lowering A/C electrical consumption.',
        },
      },
      {
        id: 'PIPE-2-045',
        type: 'pipe',
        system: 'Plumbing',
        floor: 2,
        room: 'Level 2 Master Bath',
        assembly: '3" Schedule 40 PVC Sanitary Waste Stack connecting to Main Sewer Line',
        materials: [
          { name: '3" Schedule 40 PVC DWV Pipe', specification: 'ASTM D2665 Solvent Weld Joints', quantity: 48, unit: 'lin ft' },
          { name: 'PVC Solvent Cement & Primer', specification: 'Low-VOC Heavy Duty PVC Cement', quantity: 2, unit: 'ea' },
        ],
        geometry: { position: [8, 14, 2], dimensions: [0.25, 0.25, 48] },
        isExterior: false,
        exposure: 'Interior Concealed Pipe Chase',
        connectedComponentIds: ['FIXTURE-2-001', 'PIPE-1-001'],
        openings: [],
        quantity: { value: 48, unit: 'lin ft' },
        unitCost: 8.5,
        totalCost: 408,
        installationStageDay: 22,
        inspectionState: 'passed',
        inspectionNotes: 'Verified 1/4" per foot slope on 3" sanitary line.',
        whySelected: {
          reason: 'Schedule 40 PVC provides smooth flow hydraulics and chemical resistance for sanitary waste.',
          environmentalFactor: 'Non-corrosive material impervious to ground soil acidity.',
          codeRule: 'Florida Plumbing Code Section 704.1 slope requirements.',
          alternativesConsidered: ['Cast Iron Soil Pipe', 'ABS Pipe'],
          costImpact: 'Standard economical plumbing material.',
          lifecycleNotes: 'Solvent welded joints guarantee zero leak integrity when installed at correct slope.',
        },
      },
      {
        id: 'PANEL-1-MAIN',
        type: 'panel',
        system: 'Electrical',
        floor: 1,
        room: 'Garage Equipment Bay',
        assembly: '200A 120/240V 42-Space Main Breaker Distribution Panel + Surge Protective Device (SPD)',
        materials: [
          { name: '200A Main Breaker Panelboard', specification: 'NEMA 1 Indoor Enclosure, UL 67', quantity: 1, unit: 'ea' },
          { name: 'Type 2 Surge Protective Device (SPD)', specification: '50kA Surge Current Rating', quantity: 1, unit: 'ea' },
          { name: 'Combination AFCI/GFCI Breakers', specification: 'NEC 2023 Compliant 15A & 20A', quantity: 28, unit: 'ea' },
        ],
        geometry: { position: [-18, 5, -12], dimensions: [1.2, 2.5, 0.4] },
        isExterior: false,
        exposure: 'Garage Protected Wall Bay',
        connectedComponentIds: ['RECEPTACLE-1-022'],
        openings: [],
        quantity: { value: 1, unit: 'ea' },
        unitCost: 1250,
        totalCost: 1250,
        installationStageDay: 25,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Centralized 200A panel with surge protection defends sensitive household electronics against Florida lightning surges.',
          environmentalFactor: 'Tampa area ranks #1 in U.S. for cloud-to-ground lightning strikes per square mile.',
          codeRule: 'NEC 2023 Section 242.50 mandatory surge protection for dwelling units.',
          alternativesConsidered: ['150A Main Panel without SPD'],
          costImpact: 'Protects thousands of dollars in connected home equipment.',
          lifecycleNotes: 'SPD status LED provides instant operational confirmation.',
        },
      },
    ],
    inspectionTickets: [],
    bom: [],
    suppliers: [
      {
        id: 'SUP-001',
        name: 'CEMEX Florida Ready-Mix Plant #14',
        category: 'Concrete & Masonry',
        address: '4102 S 50th St, Tampa, FL 33619',
        distanceMiles: 8.4,
        rating: 4.8,
        leadTimeDays: 1,
        verifiedProducts: [
          { name: '4000 PSI Ready-Mix Concrete', price: 165, unit: 'cu yd', availability: 'In Stock' },
          { name: '3000 PSI Fine Masonry Grout', price: 145, unit: 'cu yd', availability: 'In Stock' },
        ],
      },
      {
        id: 'SUP-002',
        name: 'Gulf Coast Metal Roofing Supply',
        category: 'Roofing & Metals',
        address: '6810 E Hanna Ave, Tampa, FL 33610',
        distanceMiles: 11.2,
        rating: 4.9,
        leadTimeDays: 5,
        verifiedProducts: [
          { name: '24-Ga Galvalume Standing Seam Metal', price: 14.2, unit: 'sq ft', availability: '3-5 Days' },
          { name: 'Self-Adhered High-Temp Underlayment', price: 0.85, unit: 'sq ft', availability: 'In Stock' },
        ],
      },
    ],
    schedule: [],
    changeOrderRisks: [],
    score: {
      overall: 88.5,
      completeness: 94.0,
      structuralValidation: 96.0,
      mepConnectivity: 85.0,
      clashFreePercentage: 92.0,
      codeValidation: 90.0,
      environmentalAppropriateness: 96.0,
      materialCompleteness: 91.0,
      inspectionSuccess: 88.0,
      constructability: 90.0,
      costConfidence: 92.0,
      changeOrderRisk: 84.0,
    },
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'HOTEL-FL-00127',
    name: 'Tampa Coastal 2-Story Residence #00127',
    buildingType: 'Residential Single-Family',
    gymLevel: 3,
    iterationNumber: 42,
    overallCompletionPct: 82.4,
    status: 'inspecting',
    environment: {
      latitude: 27.9506,
      longitude: -82.4572,
      locationName: 'Tampa Bay Coastal Corridor, Florida',
      jurisdiction: 'City of Tampa / Hillsborough County',
      climateZone: 'Zone 2A (Hot-Humid)',
      coastalProximityMiles: 1.2,
      saltExposureRisk: 'High',
      windSpeedMph: 150,
      rainfallInchesYear: 51.5,
      humidityPctAvg: 74,
      minTempF: 38,
      maxTempF: 96,
      freezeThawCycles: 0,
      seismicCategory: 'Category A (Low Risk)',
      wildfireRisk: 'Low',
      floodZone: 'AE (Base Flood Elev 11 ft)',
      soilBearingCapacityPsf: 2000,
      groundwaterTableFt: 4.5,
      utilitiesAvailable: ['Municipal Water', 'Sanitary Sewer', 'Underground Electric 240V', 'Fiber Optic'],
      localCodeVersion: 'Florida Building Code 8th Edition (2023)',
    },
    components: [
      {
        id: 'SLAB-1-001',
        type: 'slab',
        system: 'Structure',
        floor: 1,
        room: 'Building Base Foundation',
        assembly: '6" Monolithic Post-Tensioned Concrete Slab over 15 mil Stego Wrap Vapor Barrier & 4" Clean Gravel',
        materials: [
          { name: '4000 PSI Ready-Mix Concrete', specification: 'ACI 318 Exposure Class F0, S1, C1, W1', quantity: 48, unit: 'cu yd' },
          { name: '1/2" Post-Tensioning Steel Strands', specification: 'ASTM A416 Grade 270 Unbonded', quantity: 1850, unit: 'lin ft' },
          { name: '#5 Rebar Perimeter Stem Wall', specification: 'ASTM A615 Grade 60', quantity: 920, unit: 'lin ft' },
        ],
        geometry: { position: [0, 0, 0], dimensions: [42, 0.5, 32] },
        fireRatingHours: 2,
        isExterior: true,
        exposure: 'Ground Contact / Moisture Risk',
        connectedComponentIds: ['WALL-1-101', 'WALL-1-102', 'FOOTING-1-001'],
        openings: [],
        quantity: { value: 48, unit: 'cu yd' },
        unitCost: 165,
        totalCost: 7920,
        installationStageDay: 3,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Post-tensioned monolithic slab resists soil settlement on sandy coastal Florida soil.',
          environmentalFactor: 'Groundwater table at 4.5 ft requires 15 mil heavy vapor barrier to eliminate capillary moisture drive.',
          codeRule: 'Florida Building Code Section 1808 shallow foundation requirements.',
          alternativesConsidered: ['Stem wall with raised wood floor', 'Deep driven concrete piles'],
          costImpact: 'Saves 18% cost vs deep piling while maintaining structural load integrity.',
          lifecycleNotes: 'Zero corrosion risk when post-tension tendons are grease-encapsulated.',
        },
      },
      {
        id: 'WALL-1-101',
        type: 'wall',
        system: 'Structure',
        floor: 1,
        room: 'Level 1 Exterior Perimeter',
        assembly: '8" CMU Concrete Block Masonry + Rebar Reinforced Cells + Exterior Stucco + Interior Metal Furring & 5/8" Type-X Gypsum',
        materials: [
          { name: '8x8x16 Lightweight CMU Block', specification: 'ASTM C90 Grade N Type 1', quantity: 1420, unit: 'ea' },
          { name: '3000 PSI Masonry Grout Fill', specification: 'ASTM C476 Fine Grout', quantity: 18, unit: 'cu yd' },
          { name: '#4 Vertical Rebar @ 32" o.c.', specification: 'ASTM A615 Grade 60', quantity: 680, unit: 'lin ft' },
          { name: '5/8" Type-X Gypsum Board', specification: 'ASTM C1396 Fire-Rated', quantity: 1680, unit: 'sq ft' },
        ],
        geometry: { position: [0, 5, -16], dimensions: [42, 10, 0.67] },
        fireRatingHours: 2,
        acousticSTC: 52,
        isExterior: true,
        exposure: 'Exterior Coastal Exposure / 150 MPH Wind',
        connectedComponentIds: ['SLAB-1-001', 'SLAB-2-001', 'WINDOW-1-001'],
        openings: ['WINDOW-1-001', 'DOOR-1-001'],
        quantity: { value: 420, unit: 'sq ft' },
        unitCost: 18.5,
        totalCost: 7770,
        installationStageDay: 8,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Grouted CMU masonry delivers wind resistance against 150 MPH hurricane projectiles.',
          environmentalFactor: 'Salt spray & high humidity destroy unprotected wood exterior framing at ground level.',
          codeRule: 'HVHZ High Velocity Hurricane Zone wall mass requirement.',
          alternativesConsidered: ['2x6 Wood Frame Wall', 'Insulated Concrete Forms (ICF)'],
          costImpact: 'Optimal local labor availability in Florida mason market.',
          lifecycleNotes: '50+ year structural lifespan with zero rot risk.',
        },
      },
      {
        id: 'ROOF-2-001',
        type: 'roof',
        system: 'Envelope',
        floor: 2,
        room: 'Roof System',
        assembly: 'Engineered Wood Hip Truss @ 24" o.c. + 5/8" CDX Deck + Self-Adhered Secondary Water Barrier + 24-Ga Galvalume Standing Seam Metal Panels',
        materials: [
          { name: '24-Ga Galvalume Standing Seam Metal', specification: 'Kynar 500 Finish, 150 MPH Rated', quantity: 1620, unit: 'sq ft' },
          { name: '5/8" CDX Exterior Plywood Sheathing', specification: 'APA Rated Sheathing Exposure 1', quantity: 1620, unit: 'sq ft' },
          { name: 'Self-Adhered Ice & Water Shield WRB', specification: 'ASTM D1970 High Temp Membrane', quantity: 1620, unit: 'sq ft' },
        ],
        geometry: { position: [0, 22, 0], dimensions: [44, 6, 34] },
        fireRatingHours: 1,
        isExterior: true,
        exposure: '150 MPH Wind / Direct Sunlight UV',
        connectedComponentIds: ['WALL-2-101'],
        openings: [],
        quantity: { value: 1620, unit: 'sq ft' },
        unitCost: 14.2,
        totalCost: 23004,
        installationStageDay: 18,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Hip roof geometry offers maximum aerodynamic resistance against hurricane wind uplift forces.',
          environmentalFactor: 'Galvalume coating resists salt air corrosion superior to standard galvanized steel.',
          codeRule: 'Florida Building Code Section 1507 metal roof uplift load test compliance.',
          alternativesConsidered: ['Architectural Asphalt Shingles', 'Concrete Roof Tile'],
          costImpact: '2.2x cost of asphalt shingle, offset by insurance discount and 40-year durability.',
          lifecycleNotes: 'Reflects 70% solar radiation, drastically lowering A/C electrical consumption.',
        },
      },
      {
        id: 'PIPE-2-045',
        type: 'pipe',
        system: 'Plumbing',
        floor: 2,
        room: 'Level 2 Bath Corridor',
        assembly: '3" Schedule 40 PVC Sanitary Waste Stack connecting to Main Sewer Line',
        materials: [
          { name: '3" Schedule 40 PVC DWV Pipe', specification: 'ASTM D2665 Solvent Weld Joints', quantity: 45, unit: 'lin ft' },
          { name: 'PVC Solvent Cement & Primer', specification: 'Low-VOC Heavy Duty PVC Cement', quantity: 2, unit: 'ea' },
        ],
        geometry: { position: [8, 14, 2], dimensions: [0.25, 0.25, 45] },
        isExterior: false,
        exposure: 'Interior Concealed Pipe Chase',
        connectedComponentIds: ['FIXTURE-2-001', 'PIPE-1-001'],
        openings: [],
        quantity: { value: 45, unit: 'lin ft' },
        unitCost: 8.5,
        totalCost: 382.5,
        installationStageDay: 22,
        inspectionState: 'failed',
        inspectionNotes: 'Modeled drain slope measured at 1/8" per foot; Florida Plumbing Code requires minimum 1/4" per foot slope for 3" pipe.',
        whySelected: {
          reason: 'Schedule 40 PVC provides smooth flow hydraulics and chemical resistance for sanitary waste.',
          environmentalFactor: 'Non-corrosive material impervious to ground soil acidity.',
          codeRule: 'Florida Plumbing Code Section 704.1 slope requirements.',
          alternativesConsidered: ['Cast Iron Soil Pipe', 'ABS Pipe'],
          costImpact: 'Standard economical plumbing material.',
          lifecycleNotes: 'Solvent welded joints guarantee zero leak integrity when installed at correct slope.',
        },
      },
      {
        id: 'DUCT-1-012',
        type: 'duct',
        system: 'HVAC',
        floor: 1,
        room: 'Living Room Trunk Line',
        assembly: 'R-8 Insulated Flexible Ductwork running from 16 SEER2 Heat Pump Air Handler',
        materials: [
          { name: '10" Round R-8 Insulated Flex Duct', specification: 'UL 181 Class 1 Flexible Air Duct', quantity: 65, unit: 'lin ft' },
          { name: 'Galvanized Sheet Metal Trunk Supply', specification: '26 Gauge ASTM A653', quantity: 24, unit: 'lin ft' },
        ],
        geometry: { position: [-6, 9, 4], dimensions: [0.83, 0.83, 65] },
        isExterior: false,
        exposure: 'Conditioned Attic / Floor Cavity',
        connectedComponentIds: ['AHU-1-001', 'DIFFUSER-1-001'],
        openings: [],
        quantity: { value: 65, unit: 'lin ft' },
        unitCost: 11.0,
        totalCost: 715,
        installationStageDay: 24,
        inspectionState: 'passed',
        whySelected: {
          reason: 'R-8 insulation prevents condensation in high-humidity Florida climate.',
          environmentalFactor: '74% average ambient outdoor humidity demands sealed R-8 minimum insulation to avoid attic mold.',
          codeRule: 'Florida Energy Conservation Code Section C403.2.7 duct insulation.',
          alternativesConsidered: ['R-6 Flex Duct', 'Uninsulated Duct Board'],
          costImpact: 'Minimal cost addition yielding major energy savings.',
          lifecycleNotes: 'Sealed mastic joints prevent duct leakage loss below 3%.',
        },
      },
      {
        id: 'RECEPTACLE-1-022',
        type: 'receptacle',
        system: 'Electrical',
        floor: 1,
        room: 'Wet Bar / Kitchen Island',
        assembly: '20A 125V Tamper-Resistant Weather-Resistant SmartLockPro GFCI Receptacle',
        materials: [
          { name: '20A Commercial GFCI Outlet', specification: 'UL 943 Class A Self-Testing', quantity: 1, unit: 'ea' },
          { name: '12/2 THHN Copper Wire in EMT', specification: 'ASTM B3 Solid Copper', quantity: 35, unit: 'lin ft' },
        ],
        geometry: { position: [12, 3.5, 6], dimensions: [0.2, 0.3, 0.2] },
        isExterior: false,
        exposure: 'Interior Near Water Sink Source',
        connectedComponentIds: ['PANEL-1-001'],
        openings: [],
        quantity: { value: 1, unit: 'ea' },
        unitCost: 28,
        totalCost: 28,
        installationStageDay: 26,
        inspectionState: 'passed',
        whySelected: {
          reason: 'Mandatory personnel shock protection within 6 feet of plumbing water fixtures.',
          environmentalFactor: 'High indoor humidity near sinks increases electrical conductivity risk.',
          codeRule: 'NEC 2023 Section 210.8(A) Ground-Fault Circuit-Interrupter Protection.',
          alternativesConsidered: ['Standard 15A Receptacle', 'GFCI Circuit Breaker at Panel'],
          costImpact: '$28 outlet vs $95 breaker.',
          lifecycleNotes: 'Self-testing automated feature ensures continuous shock protection.',
        },
      },
    ],
    inspectionTickets: [
      {
        id: 'PLUMB-002918',
        projectId: 'HOTEL-FL-00127',
        inspectorAgent: 'Plumbing Inspector Swarm',
        severity: 'critical',
        affectedComponentIds: ['PIPE-2-045'],
        location: 'Level 2 Bath Corridor (PIPE-2-045)',
        problem: 'Insufficient modeled sanitary pipe slope. Measured at 1/8" per foot.',
        requiredStandard: 'Florida Plumbing Code Section 704.1 requires minimum 1/4" per foot slope for 3" diameter pipe.',
        actualCondition: 'Pipe modeled horizontally with only 0.125 in/ft fall.',
        status: 'open',
        repairAgentAssigned: 'Plumbing Repair Sub-Agent',
        proposedRepair: 'Adjust pipe hanger elevation drop by 0.5 inches over 20ft run to achieve 0.25 in/ft slope.',
        timestamp: '2026-08-20T09:14:02Z',
      },
      {
        id: 'ELEV-00104',
        projectId: 'HOTEL-FL-00127',
        inspectorAgent: 'Life-Safety & Elevation Inspector',
        severity: 'high',
        affectedComponentIds: ['SLAB-1-001'],
        location: 'Level 1 Building Finished Floor Elevation',
        problem: 'Slab top elevation is 10.5 ft NAVD88; Flood Zone AE Base Flood Elevation is 11.0 ft NAVD88.',
        requiredStandard: 'ASCE 24-14 / Florida Building Code requires Finished Floor Elevation minimum +1 ft above BFE (12.0 ft).',
        actualCondition: 'Building finished floor modeled 1.5 ft below mandatory flood elevation line.',
        status: 'open',
        repairAgentAssigned: 'Site & Foundation Repair Agent',
        proposedRepair: 'Add 18" engineered compacted fill soil pad under slab to raise finished floor elevation to +12.5 ft NAVD88.',
        timestamp: '2026-08-20T09:30:15Z',
      },
      {
        id: 'ENVELOPE-00311',
        projectId: 'HOTEL-FL-00127',
        inspectorAgent: 'Envelope & Hurricane Inspector',
        severity: 'medium',
        affectedComponentIds: ['ROOF-2-001'],
        location: 'Roof Truss to Wall Plate Tie-Down Fasteners',
        problem: 'Truss hurricane clip fastener spec lists electro-galvanized nails.',
        requiredStandard: 'FBC HVHZ Section 2319 requires Hot-Dip Galvanized or Stainless Steel 316 clips within 2 miles of saltwater coast.',
        actualCondition: 'Electro-galvanized fasteners specified, prone to premature salt air rust.',
        status: 'open',
        repairAgentAssigned: 'Materials & Structure Repair Agent',
        proposedRepair: 'Update fastener schedule to Simpson Strong-Tie HDG / SS316 Hurricane Straps with SS ring-shank nails.',
        timestamp: '2026-08-20T09:45:00Z',
      },
    ],
    bom: [], // Generated dynamically
    suppliers: [
      {
        id: 'SUP-001',
        name: 'CEMEX Florida Ready-Mix Plant #14',
        category: 'Concrete & Masonry',
        address: '4102 S 50th St, Tampa, FL 33619',
        distanceMiles: 8.4,
        rating: 4.8,
        leadTimeDays: 1,
        verifiedProducts: [
          { name: '4000 PSI Ready-Mix Concrete', price: 165, unit: 'cu yd', availability: 'In Stock' },
          { name: '3000 PSI Fine Masonry Grout', price: 145, unit: 'cu yd', availability: 'In Stock' },
        ],
      },
      {
        id: 'SUP-002',
        name: 'Gulf Coast Metal Roofing Supply',
        category: 'Roofing & Metals',
        address: '6810 E Hanna Ave, Tampa, FL 33610',
        distanceMiles: 11.2,
        rating: 4.9,
        leadTimeDays: 5,
        verifiedProducts: [
          { name: '24-Ga Galvalume Standing Seam Metal', price: 14.2, unit: 'sq ft', availability: '3-5 Days' },
          { name: 'Self-Adhered High-Temp Underlayment', price: 0.85, unit: 'sq ft', availability: 'In Stock' },
        ],
      },
      {
        id: 'SUP-003',
        name: 'Ferguson Plumbing Supply Hub',
        category: 'Plumbing',
        address: '5410 W Sligh Ave, Tampa, FL 33634',
        distanceMiles: 6.8,
        rating: 4.7,
        leadTimeDays: 1,
        verifiedProducts: [
          { name: '3" Schedule 40 PVC DWV Pipe', price: 8.5, unit: 'lin ft', availability: 'In Stock' },
          { name: 'Schedule 40 PVC Solvent Cement', price: 12.5, unit: 'ea', availability: 'In Stock' },
        ],
      },
      {
        id: 'SUP-004',
        name: 'City Electric Supply Depot',
        category: 'Electrical',
        address: '3902 W Hillsborough Ave, Tampa, FL 33614',
        distanceMiles: 5.1,
        rating: 4.8,
        leadTimeDays: 1,
        verifiedProducts: [
          { name: '20A Commercial GFCI Outlet', price: 28, unit: 'ea', availability: 'In Stock' },
          { name: '12/2 THHN Solid Copper Wire', price: 0.65, unit: 'lin ft', availability: 'In Stock' },
        ],
      },
    ],
    schedule: [
      {
        id: 'TASK-001',
        dayStart: 1,
        dayEnd: 4,
        stageName: 'Site Prep & Post-Tensioned Foundation Slab',
        trade: 'Concrete & Masonry',
        dependentTaskIds: [],
        componentIds: ['SLAB-1-001'],
        equipmentRequired: ['Laser Transit Level', 'Concrete Pump Truck', 'Vibratory Screed'],
        status: 'completed',
      },
      {
        id: 'TASK-002',
        dayStart: 5,
        dayEnd: 12,
        stageName: 'CMU Block Exterior Walls & Grout Pour',
        trade: 'Masonry',
        dependentTaskIds: ['TASK-001'],
        componentIds: ['WALL-1-101'],
        equipmentRequired: ['Scaffolding', 'Grout Pump', 'Rebar Cutters'],
        status: 'completed',
      },
      {
        id: 'TASK-003',
        dayStart: 13,
        dayEnd: 19,
        stageName: 'Roof Truss Sheathing & Standing Seam Metal Installation',
        trade: 'Roofing & Metals',
        dependentTaskIds: ['TASK-002'],
        componentIds: ['ROOF-2-001'],
        equipmentRequired: ['Crane 40-Ton', 'Seamer Machine', 'Safety Harness Rig'],
        status: 'completed',
      },
      {
        id: 'TASK-004',
        dayStart: 20,
        dayEnd: 25,
        stageName: 'Rough MEP Rough-In (Plumbing, Electrical, HVAC Flex Duct)',
        trade: 'Plumbing / HVAC / Electrical',
        dependentTaskIds: ['TASK-003'],
        componentIds: ['PIPE-2-045', 'DUCT-1-012', 'RECEPTACLE-1-022'],
        equipmentRequired: ['Pipe Threader', 'Duct Mastic Press', 'Cable Puller'],
        status: 'in_progress',
      },
      {
        id: 'TASK-005',
        dayStart: 26,
        dayEnd: 30,
        stageName: 'Independent Inspection & Automated Failure Repair Loop',
        trade: 'Quality Assurance & Inspector Swarm',
        dependentTaskIds: ['TASK-004'],
        componentIds: ['PIPE-2-045', 'SLAB-1-001', 'ROOF-2-001'],
        equipmentRequired: ['Laser Slope Gauge', 'Borescope Camera', 'Moisture Meter'],
        status: 'pending',
      },
    ],
    changeOrderRisks: [
      {
        id: 'RISK-001',
        issue: 'Sanitary pipe slope deficiency (PIPE-2-045) will cause sewer backup if uncorrected.',
        probability: 'high',
        severity: 'critical',
        potentialCost: 4500,
        scheduleImpactDays: 1,
        affectedTrades: ['Plumbing', 'Drywall'],
        recommendedMitigation: 'Execute Repair Swarm action to drop hanger brackets 0.5" before drywall enclosing.',
        resolved: false,
      },
      {
        id: 'RISK-002',
        issue: 'Slab finished floor elevation below mandatory Base Flood Elevation line.',
        probability: 'high',
        severity: 'critical',
        potentialCost: 12800,
        scheduleImpactDays: 3,
        affectedTrades: ['Site / Earthwork', 'Concrete'],
        recommendedMitigation: 'Add 18" compacted structural fill pad under slab to reach +12.5 ft NAVD88 elevation.',
        resolved: false,
      },
      {
        id: 'RISK-003',
        issue: 'Roof truss hurricane clip fastener corrosion near salt water.',
        probability: 'medium',
        severity: 'medium',
        potentialCost: 1200,
        scheduleImpactDays: 0,
        affectedTrades: ['Roofing', 'Framing'],
        recommendedMitigation: 'Swap electro-galvanized fasteners to 316 Stainless Steel prior to inspection sign-off.',
        resolved: false,
      },
    ],
    score: {
      overall: 84.6,
      completeness: 92.0,
      structuralValidation: 95.0,
      mepConnectivity: 78.0,
      clashFreePercentage: 88.0,
      codeValidation: 81.0,
      environmentalAppropriateness: 96.0,
      materialCompleteness: 90.0,
      inspectionSuccess: 72.0,
      constructability: 89.0,
      costConfidence: 94.0,
      changeOrderRisk: 75.0,
    },
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-08-20T10:15:00Z',
  },

  {
    id: 'TOWN-IN-00201',
    name: 'Indianapolis Freeze/Thaw Townhome #00201',
    buildingType: 'Residential Multi-Family',
    gymLevel: 4,
    iterationNumber: 18,
    overallCompletionPct: 91.2,
    status: 'completed',
    environment: {
      latitude: 39.7684,
      longitude: -86.1581,
      locationName: 'Indianapolis, Indiana',
      jurisdiction: 'City of Indianapolis / Marion County',
      climateZone: 'Zone 5A (Cold)',
      coastalProximityMiles: 520,
      saltExposureRisk: 'Low',
      windSpeedMph: 115,
      rainfallInchesYear: 42.4,
      humidityPctAvg: 68,
      minTempF: -12,
      maxTempF: 92,
      freezeThawCycles: 64,
      seismicCategory: 'Category B',
      wildfireRisk: 'Low',
      floodZone: 'Zone X (Minimal Flood Risk)',
      soilBearingCapacityPsf: 3000,
      groundwaterTableFt: 12.0,
      utilitiesAvailable: ['Municipal Water', 'Gas Grid', 'Underground Electric', 'Sewer'],
      localCodeVersion: 'Indiana Residential Code 2020',
    },
    components: [
      {
        id: 'SLAB-1-002',
        type: 'footing',
        system: 'Structure',
        floor: 0,
        room: 'Basement / Perimeter Frost Wall',
        assembly: '48" Deep Poured Concrete Frost Wall Footing over 2" Rigid Extruded Polystyrene (XPS) R-10 Insulation',
        materials: [
          { name: '3500 PSI Air-Entrained Concrete', specification: 'ACI 318 Exposure Class F2 (Freeze-Thaw)', quantity: 38, unit: 'cu yd' },
          { name: '2" Owens Corning XPS Foam Insulation', specification: 'ASTM C578 Type IV R-10', quantity: 1200, unit: 'sq ft' },
        ],
        geometry: { position: [0, -4, 0], dimensions: [40, 4, 28] },
        fireRatingHours: 2,
        isExterior: true,
        exposure: 'Subgrade Freeze/Thaw Penetration',
        connectedComponentIds: ['WALL-1-201'],
        openings: [],
        quantity: { value: 38, unit: 'cu yd' },
        unitCost: 175,
        totalCost: 6650,
        installationStageDay: 2,
        inspectionState: 'passed',
        whySelected: {
          reason: '48" footing depth extends below Indiana 36" frost penetration depth line.',
          environmentalFactor: '64 annual freeze/thaw cycles require air-entrained concrete (5.5% air voids) to prevent spalling.',
          codeRule: 'Indiana Residential Code Section R403.1.4 frost protection.',
          alternativesConsidered: ['Shallow Frost Protected Foundation (FPSF)', 'Uninsulated Stem Wall'],
          costImpact: 'Standard practice for Zone 5A cold climate basements.',
          lifecycleNotes: 'Air-entrained concrete preserves structural integrity across 100+ winter cycles.',
        },
      },
    ],
    inspectionTickets: [],
    bom: [],
    suppliers: [],
    schedule: [],
    changeOrderRisks: [],
    score: {
      overall: 94.2,
      completeness: 98.0,
      structuralValidation: 96.0,
      mepConnectivity: 95.0,
      clashFreePercentage: 97.0,
      codeValidation: 96.0,
      environmentalAppropriateness: 98.0,
      materialCompleteness: 95.0,
      inspectionSuccess: 96.0,
      constructability: 93.0,
      costConfidence: 92.0,
      changeOrderRisk: 91.0,
    },
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-19T14:20:00Z',
  },
];

// Initialize BOMs for seed projects
for (const p of INITIAL_SEED_PROJECTS) {
  p.bom = generateBOMFromComponents(p.components);
}

export const INITIAL_KNOWLEDGE_ENTITIES: KnowledgeEntity[] = [
  {
    id: 'KNOW-001',
    title: 'High-Velocity Hurricane Zone (HVHZ) Fastener Corrosion Protection',
    type: 'MATERIAL',
    status: 'APPROVED',
    provenance: 'FEMA Coastal Construction Manual & FBC HVHZ Section 2319',
    confidence: 98,
    geography: 'Coastal Southeast / Florida / Gulf Coast',
    applicableConditions: ['Salt Exposure Risk = High', 'Coastal Proximity < 5 miles', 'Wind Speed > 140 MPH'],
    sourceEvidence: 'Field failure studies show electro-galvanized nails fail within 7 years due to salt aerosol degradation.',
    connectedEntityIds: ['KNOW-002', 'KNOW-004'],
  },
  {
    id: 'KNOW-002',
    title: 'Continuous Sanitary Stack Gravity Drainage Slope Validation',
    type: 'CODE_REQUIREMENT',
    status: 'APPROVED',
    provenance: 'IPC International Plumbing Code Section 704 & Florida Plumbing Code',
    confidence: 100,
    geography: 'US Nationwide',
    applicableConditions: ['Sanitary Drainage Stack', 'Pipe Diameter <= 3 in'],
    sourceEvidence: 'Mandatory 1/4" per foot minimum slope prevents solid waste settling and sewer gas entrapment.',
    connectedEntityIds: ['KNOW-001'],
  },
  {
    id: 'KNOW-003',
    title: 'Air-Entrained Concrete for Cold Climate Freeze-Thaw Resistance',
    type: 'ASSEMBLY',
    status: 'VERIFIED',
    provenance: 'ACI 318 Exposure Class F2 & ASTM C260',
    confidence: 96,
    geography: 'Climate Zones 4, 5, 6, 7 (Cold Regions)',
    applicableConditions: ['Freeze-Thaw Cycles > 20/year', 'Slab / Footing exposed to moisture'],
    sourceEvidence: 'Microscopic air voids (4.5% - 7.5%) allow expanding frozen water relief without micro-cracking matrix.',
    connectedEntityIds: [],
  },
];

export const INITIAL_LEARNED_LESSONS: LearnedLesson[] = [
  {
    id: 'LESSON-001',
    projectId: 'HOTEL-FL-00127',
    projectName: 'Tampa Coastal 2-Story Residence #00127',
    whatWorked: 'Monolithic post-tensioned slab eliminated differential soil settlement on soft coastal sand.',
    whatFailed: 'Initial pipe modeling allowed 1/8" per foot slope on 3" sanitary line, failing plumbing inspection.',
    whatRequiredRepair: 'Lowered sanitary pipe hangers 0.5" over 20ft run to achieve required 0.25 in/ft slope.',
    reusableAssembly: 'FL-COASTAL-SLAB-PT-01 (Post-Tensioned Monolithic Slab + 15mil Stego Wrap)',
    nextGymObjective: 'Train on multi-story post-tensioned concrete elevated deck shoring sequencing.',
    timestamp: '2026-08-19T18:00:00Z',
  },
];
